### ISSUE TITLE
Fix Windows

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/c-progressbar-feedstock#1]
Please add `vc` features and please correct the `python` test dependency on Windows. Also please bump the build number after doing these things.

xref: https://github.com/conda-forge/staged-recipes/pull/3199#pullrequestreview-47693013
xref: https://github.com/conda-forge/staged-recipes/pull/3199#pullrequestreview-47693621

**Comment by horta** [comment]
In my TODO list. Will do today, thanks =)

**Comment by jakirkham** [comment]
Have pulled the packages that were built without the `vc` feature as they were not compliant. As the new packages for Windows are out and using the `vc` feature correctly, this shouldn't cause any issues. One merely needs to upgrade to them.
